### ISSUE TITLE
How can I bind files into folder?

### ISSUE THREAD

**Issue by redjo99** [19-1-skku-oss/2019-1-OSS-E2#122]
I made many codes in ProjectEuler folder, and I want to bind some files in problem4, problem5, problem6, problem7 folders. Can someone teach how to do it?

**Comment by LJW25** [comment]
I found it!
When you make a file, before write file's name write the folder's name and add '/'.
Then folder will be created!

**Comment by LJW25** [comment]
I will make folders and binding your files.

**Comment by redjo99** [comment]
Wow awesome!
Thanks a lot:)
