### ISSUE TITLE
Branch issue

### ISSUE THREAD

**Issue by ParkDongChan** [19-1-skku-oss/2019-1-OSS-E2#14]
Be careful!
If you create a branch with your own nickname, change the code. If you do not delete it, it will appear in the form of a nickname -n. 
Therefore, make sure to delete after merge.
(In the case of ParkDongChan -1, -2, -3 and -4, Merge and delete normally.)

**Comment by redjo99** [comment]
I checked the problem you mentioned.
We should delete branch right after merging!!
