### ISSUE TITLE
Bulls and Cows

### ISSUE THREAD

**Issue by redjo99** [19-1-skku-oss/2019-1-OSS-E2#18]
I'm making bulls and cows algorithm, '숫자야구' in Korean.
Latest version can get input, but the algorithm is not completed.
I'll upload updated version later which can show some outputs.

**Comment by redjo99** [comment]
Pulled request new version for some new algorithm!
I'll check an error today

**Comment by ParkDongChan** [comment]
I checked two versions you uploaded! I'll also try finding errors you made.

**Comment by redjo99** [comment]
Thanks! I found a reason for the error:)
In main function, I compared 'strike' with MAX.
However, strike variable was not initialized and it made an error!

**Comment by redjo99** [comment]
Updated new version removing an error!
Also, this version has a completed algorithm! Check my code:)

**Comment by ParkDongChan** [comment]
I understand what you say. I check it.
