### ISSUE TITLE
Gomoku

### ISSUE THREAD

**Issue by redjo99** [19-1-skku-oss/2019-1-OSS-E2#3]
I'm making Gomoku algorithms based on the renzu rules personally.
Although it's java language, I'll add it for give new algorithms.

**Comment by jeongwoo25** [comment]
Could you explain about Gomoku algorithm?
and is it an useful algorithm to be applied to any other problems?

**Comment by redjo99** [comment]
Gomoku is '오목' in Korean, a board game for making successive line with 5 pieces!
I'm not sure it helps other algorithms directly, but I expect it helps other board game algorithms.

**Comment by jeongwoo25** [comment]
I think it is very good for our project :)

**Comment by redjo99** [comment]
Adding Classes for Gomoku algorithms!
I'll close this issue after upload 5 whole Classes.

**Comment by redjo99** [comment]
Added all classes:)
