### ISSUE TITLE
Edit SelectionSort

### ISSUE THREAD

**Issue by jeongwoo25** [19-1-skku-oss/2019-1-OSS-E2#4]
- edit main function to standard version
- swap function was too inefficient, so I delete it
- array could not be constructed, so I make it by dynamic allocation
- improve interface

In my environment, it works well.
check it for your environments and if there are problems, edit it please.
If not, plz close this issue :)

**Comment by ParkDongChan** [comment]
I check it. It works well!
Thank you :)
